export const FETCH_LEARNING_PATH_REQUEST = "FETCH_LEARNING_PATH_REQUEST";
export const FETCH_LEARNING_PATH_SUCCESS = "FETCH_LEARNING_PATH_SUCCESS";
export const FETCH_LEARNING_PATH_FAILURE = "FETCH_LEARNING_PATH_FAILURE";
