export const GENERATE_SUMMARY = 'summary/GENERATE_SUMMARY';
export const GENERATE_SUMMARY_SUCCESS = 'summary/GENERATE_SUMMARY_SUCCESS';
export const GENERATE_SUMMARY_FAILURE = 'summary/GENERATE_SUMMARY_FAILURE';

export const CLEAR_SUMMARY = 'summary/CLEAR_SUMMARY';
